#!/bin/sh

sed 's/PROGRAM/A/g' |
sed 's/VARS/B/g' |
sed 's/VAR_DEFS/C/g' |
sed 's/VAR_DEF/D/g' |
sed 's/DT_TYPE/E/g' |
sed 's/FUNC/F/g' |
sed 's/AFTER_HEADER/G/g' |
sed 's/HEADER/H/g' |
sed 's/DEF_PARAMS/I/g' |
sed 's/DEF_PAR_LIST/J/g' |
sed 's/DEF_PAR/K/g' |
sed 's/BODYN/L/g' |
sed 's/BODY/M/g' |
sed 's/CMD_LIST_N/AE/g' |
sed 's/CMD_LIST/N/g' |
sed 's/CMD_FOLLOW/O/g' |
sed 's/CMD/P/g' |
sed 's/AFTER_ASSIGN/Q/g' |
sed 's/ASSIGN/R/g' |
sed 's/IF_ELSE/S/g' |
sed 's/IF/T/g' |
sed 's/WHILE/U/g' |
sed 's/CALL/W/g' |
sed 's/READLN/V/g' |
sed 's/TERM_LIST/X/g' |
sed 's/TERM_FOLLOW/Y/g' |
sed 's/TERM/Z/g' |
sed 's/EXPR/AB/g' |
sed 's/WRITE/AC/g' |
sed 's/VAR_DEF/AD/g'|

sed 's/begin/a/g' |
sed 's/enddot/b/g' |
sed 's/var/c/g' |
sed 's/id/d/g' |
sed 's/integer/e/g' |
sed 's/dt_real/f/g' |
sed 's/real/g/g' |
sed 's/boolean/h/g' |
sed 's/string/i/g' |
sed 's/function/j/g' |
sed 's/forward/k/g' |
sed 's/end/l/g' |
sed 's/if/m/g' |
sed 's/then/n/g' |
sed 's/else/o/g' |
sed 's/while/p/g' |
sed 's/do/p/g' |
sed 's/sort/r/g' |
sed 's/find/s/g' |
sed 's/length/t/g' |
sed 's/copy/u/g' |
sed 's/readln/v/g' |
sed 's/write/w/g' |
sed 's/dt_int/x/g' |
sed 's/dt_bool/y/g' |
sed 's/dt_str/z/g' |
sed 's/vyraz/?/g'|

sed 's/empty/eps/g'

exit 0
